"use client";
import {useEffect,useState} from "react";
const designs=[{n:"01",name:"The Rooted Classic",style:"Warm · Refined · Trust focused",desc:"A polished service led design with rounded photography, strong local credibility, and a clear estimate journey.",kind:"classic"},{n:"02",name:"The Hudson Editorial",style:"Bold · Cinematic · Contemporary",desc:"A dramatic full image experience with oversized typography and an editorial story built around the land.",kind:"editorial"},{n:"03",name:"The Local Craftsman",style:"Friendly · Detailed · Interactive",desc:"An approachable service showcase featuring a transformation slider, stacked offerings, and a visual process.",kind:"craft"}];
export default function Home(){const[notice,setNotice]=useState("");useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("seen")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>o.observe(x));return()=>o.disconnect()},[]);function unavailable(name:string){setNotice(`${name} will open here once its final link is connected.`);setTimeout(()=>setNotice(""),3500)}return <main>
<nav className="nav wrap"><a className="logo" href="#top"><i>SL</i><b>Steve Lyall<small>Tree Care</small></b></a><div><a href="#designs">Explore designs</a><a href="#about">About the project</a></div><a className="navCta" href="#designs">View the collection ↓</a></nav>
<section id="top" className="hero wrap"><div className="eyebrow">Hudson Valley tree care · Website collection</div><h1>One trusted business.<br/><em>Three distinct</em> ways<br/>to tell the story.</h1><div className="heroBottom"><p>Explore three thoughtfully designed landing page directions for Steve Lyall Tree Care. Each shares the same trusted service, local roots, and nature focused brand, expressed through a different visual experience.</p><a href="#designs">Choose your direction <span>↓</span></a></div><div className="rings"/><div className="branch">❦</div></section>
<section className="marquee"><div>EXPERT TREE CARE <i/> WOODSTOCK <i/> HUDSON VALLEY <i/> FULLY INSURED <i/> LOCAL EXPERTISE <i/> EXPERT TREE CARE <i/> WOODSTOCK</div></section>
<section id="designs" className="collection"><div className="wrap collectionHead reveal"><div><span>03</span><small>Design directions</small></div><h2>Explore the<br/><em>collection.</em></h2><p>Every direction is responsive, animated, and designed to turn local visitors into confident enquiries.</p></div>
<div className="wrap cards">{designs.map((d,i)=><article className="design reveal" key={d.n}><div className="browser"><div className="browserbar"><span/><span/><span/><b>stevelyalltreecare.com</b></div><Mock kind={d.kind}/><div className="hoverHint">Preview design {d.n}</div></div><div className="designInfo"><div className="number">{d.n}</div><div><p>{d.style}</p><h3>{d.name}</h3><p className="desc">{d.desc}</p></div><button onClick={()=>unavailable(d.name)}>View this site <span>↗</span></button></div></article>)}</div></section>
<section id="about" className="promise"><div className="wrap promiseGrid reveal"><p>Built around one clear promise</p><h2>Professional tree care,<br/><em>rooted in local trust.</em></h2><div className="pillars"><span><b>01</b>Same trusted story</span><span><b>02</b>Three visual directions</span><span><b>03</b>One confident choice</span></div></div></section>
<section className="final wrap reveal"><div><p>Ready when you are</p><h2>Which design feels<br/>most like Steve?</h2></div><div><p>Review each direction, compare the experience, then connect the final links when the preferred design is ready to move forward.</p><a href="#designs">Explore all three <span>↑</span></a></div></section>
<footer className="footer wrap"><a className="logo" href="#top"><i>SL</i><b>Steve Lyall<small>Tree Care</small></b></a><p>Three landing page directions<br/>for one trusted local business.</p><small>© 2026 Steve Lyall Tree Care · Design showcase</small></footer>
{notice&&<div className="toast" role="status">{notice}</div>}</main>}
function Mock({kind}:{kind:string}){if(kind==="editorial")return <div className="mock editorial"><div className="miniNav">✳ STEVE LYALL <span>ABOUT　SERVICES　CONTACT　<b>FREE ESTIMATE</b></span></div><div className="miniLabel">HUDSON VALLEY TREE SPECIALISTS</div><h4>Expert Tree Care.<br/><em>Rooted in the</em><br/>Hudson Valley.</h4><button>START YOUR PROJECT ↗</button></div>;if(kind==="craft")return <div className="mock craft"><div className="miniNav">SL STEVE LYALL <span>ABOUT　 SERVICES　 WORK　 <b>FREE QUOTE</b></span></div><div><small>TRUSTED LOCAL TREE SPECIALISTS</small><h4>Expert Tree Care.<br/><em>Rooted in the</em><br/>Hudson Valley.</h4><p>Careful work. Local knowledge. A clean finish.</p><button>GET A FREE ESTIMATE</button></div><div className="arch"/></div>;return <div className="mock classic"><div className="miniNav">SL STEVE LYALL <span>ABOUT　SERVICES　WORK　<b>FREE ESTIMATE</b></span></div><div><small>HUDSON VALLEY TREE SPECIALISTS</small><h4>Expert Tree Care.<br/><em>Rooted in the</em><br/>Hudson Valley.</h4><p>Local expertise. Safety first. Immaculate cleanups.</p><button>GET A FREE ESTIMATE</button></div><div className="oval"/></div>}
